version: 2.1

aliases:
  - &runner
    executor:
      name: node/default
      tag: << parameters.node-version >>
  - &size
    resource_class: small
  - &params
    parameters:
      node-version:
        type: string

orbs:
  node: circleci/node@4

jobs:
  lint:
    <<: *runner
    <<: *size
    <<: *params
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

workflows:
  build:
    jobs:
      - lint:
          node-version: lts
